# 20% 55.16 -> 56.92 = 1.66
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 2 --experiment_name webqsp_scratch2_0 1>./logs/webqsp_scratch2_0.log 2>&1
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 2 --ckpt_4_embedding webqsp_scratch2_0-h1.ckpt --ckpt_4_pretrain CFQ_10-3.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine2_0 1>./logs/webqsp_fine2_0.log 2>&1
# -> 56.13
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 2 --ckpt_4_embedding webqsp_scratch2_0-h1.ckpt --ckpt_4_pretrain CFQ_10-7.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine2_1 1>./logs/webqsp_fine2_1.log 2>&1
# -> 58.27 = 3.11
CUDA_VISIBLE_DEVICES=1 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 2 --ckpt_4_embedding webqsp_scratch2_0-h1.ckpt --ckpt_4_pretrain CFQ_10-1.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine2_2 1>./logs/webqsp_fine2_2.log 2>&1 &
# -> 57.17 = 2.01
CUDA_VISIBLE_DEVICES=1 nohup python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 2 --ckpt_4_embedding webqsp_scratch2_0-h1.ckpt --ckpt_4_pretrain CFQ_10-5.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine2_3 1>./logs/webqsp_fine2_3.log 2>&1 &

# 40% 59.85 -> 56.25 = -3.6
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 4 --experiment_name webqsp_scratch4_0 1>./logs/webqsp_scratch4_0.log 2>&1
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 4 --ckpt_4_embedding webqsp_scratch4_0-h1.ckpt --ckpt_4_pretrain CFQ_10-3.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine4_0 1>./logs/webqsp_fine4_0.log 2>&1
# -> 65.16 = 5.31
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 4 --ckpt_4_embedding webqsp_scratch4_0-h1.ckpt --ckpt_4_pretrain CFQ_10-1.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine4_1 1>./logs/webqsp_fine4_1.log 2>&1
# -> 65.16 = 5.31
CUDA_VISIBLE_DEVICES=1 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 4 --ckpt_4_embedding webqsp_scratch4_0-h1.ckpt --ckpt_4_pretrain CFQ_10-5.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine4_2 1>./logs/webqsp_fine4_2.log 2>&1

# 60% 66.32 -> 68.76 = 2.44
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 6 --experiment_name webqsp_scratch6_0 1>./logs/webqsp_scratch6_0.log 2>&1
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 6 --ckpt_4_embedding webqsp_scratch6_0-h1.ckpt --ckpt_4_pretrain CFQ_10-3.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine6_0 1>./logs/webqsp_fine6_0.log 2>&1
# -> 65.89
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 6 --ckpt_4_embedding webqsp_scratch6_0-h1.ckpt --ckpt_4_pretrain CFQ_10-1.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine6_1 1>./logs/webqsp_fine6_1.log 2>&1
# -> 68.94 = 2.62
CUDA_VISIBLE_DEVICES=1 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 6 --ckpt_4_embedding webqsp_scratch6_0-h1.ckpt --ckpt_4_pretrain CFQ_10-5.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine6_2 1>./logs/webqsp_fine6_2.log 2>&1

# 80% 65.95 -> 70.10 = 5.05
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 8 --experiment_name webqsp_scratch8_0 1>./logs/webqsp_scratch8_0.log 2>&1
# -> 71.02 = 5
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 8 --ckpt_4_embedding webqsp_scratch8_0-h1.ckpt --ckpt_4_pretrain CFQ_10-3.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine8_0 1>./logs/webqsp_fine8_0.log 2>&1
# -> 70.77 = 5
CUDA_VISIBLE_DEVICES=1 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 8 --ckpt_4_embedding webqsp_scratch8_0-h1.ckpt --ckpt_4_pretrain CFQ_10-5.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine8_2 1>./logs/webqsp_fine8_2.log 2>&1

# 100% 71.87 -> 72.67 = 0.80

# webqsp
# 45.21 -> 56.92
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 2 --experiment_name webqsp_scratch2_1 1>./logs/webqsp_scratch2_1.log 2>&1
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 2 --ckpt_4_embedding webqsp_scratch2_1-h1.ckpt --ckpt_4_pretrain CFQ_11-5.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine2_4 1>./logs/webqsp_fine2_4.log 2>&1
# 54.97 -> 64.12
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 4 --experiment_name webqsp_scratch4_1 1>./logs/webqsp_scratch4_1.log 2>&1
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 20 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 4 --ckpt_4_embedding webqsp_scratch4_1-h1.ckpt --ckpt_4_pretrain CFQ_11-5.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine4_3 1>./logs/webqsp_fine4_3.log 2>&1
# 67.42 -> 67.72
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 6 --experiment_name webqsp_scratch6_1 1>./logs/webqsp_scratch6_1.log 2>&1
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 6 --experiment_name webqsp_scratch6_1_1 1>./logs/webqsp_scratch6_1_1.log 2>&1
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 6 --ckpt_4_embedding webqsp_scratch6_1-h1.ckpt --ckpt_4_pretrain CFQ_11-5.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine6_3 1>./logs/webqsp_fine6_3.log 2>&1
# 66.08 -> 68.33
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 8 --experiment_name webqsp_scratch8_1 1>./logs/webqsp_scratch8_1.log 2>&1
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder ~/work/QA/KBQA/datasets/webqsp/ --checkpoint_dir ~/work/QA/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 8 --ckpt_4_embedding webqsp_scratch8_1-h1.ckpt --ckpt_4_pretrain CFQ_11-5.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine8_3 1>./logs/webqsp_fine8_3.log 2>&1

# CWQ
# 38.83 -> 38.23
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 2 --experiment_name CWQ_scratch2 1>./logs/CWQ_scratch2.log 2>&1
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 2 --ckpt_4_embedding CWQ_scratch2-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_reasoning --experiment_name CWQ_fine2 1>./logs/CWQ_fine2.log 2>&1
CUDA_VISIBLE_DEVICES=4 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/type_group/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 150 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --early_stop_patience 25 --filter --load_experiment "CWQ_scratch2-h1.ckpt" --is_eval --eval_different_type
CUDA_VISIBLE_DEVICES=3 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/type_group/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 150 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --early_stop_patience 25 --filter --load_experiment "CWQ_fine2-h1.ckpt" --is_eval --eval_different_type
# 43.42 -> 43.84
CUDA_VISIBLE_DEVICES=1 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 4 --experiment_name CWQ_scratch4 1>./logs/CWQ_scratch4.log 2>&1
CUDA_VISIBLE_DEVICES=1 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 40 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 4 --ckpt_4_embedding CWQ_scratch4-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_reasoning --experiment_name CWQ_fine4 1>./logs/CWQ_fine4.log 2>&1
CUDA_VISIBLE_DEVICES=4 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/type_group/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 150 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --early_stop_patience 25 --filter --load_experiment "CWQ_scratch4-h1.ckpt" --is_eval --eval_different_type
CUDA_VISIBLE_DEVICES=7 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/type_group/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 150 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --early_stop_patience 25 --filter --load_experiment "CWQ_fine4-h1.ckpt" --is_eval --eval_different_type
# 44.21 -> 46.50
CUDA_VISIBLE_DEVICES=4 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 6 --experiment_name CWQ_scratch6 1>./logs/CWQ_scratch6.log 2>&1
CUDA_VISIBLE_DEVICES=4 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 6 --ckpt_4_embedding CWQ_scratch6-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_reasoning --experiment_name CWQ_fine6 1>./logs/CWQ_fine6.log 2>&1
CUDA_VISIBLE_DEVICES=4 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/type_group/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 150 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --early_stop_patience 25 --filter --load_experiment "CWQ_scratch6-h1.ckpt" --is_eval --eval_different_type
CUDA_VISIBLE_DEVICES=3 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/type_group/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 150 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --early_stop_patience 25 --filter --load_experiment "CWQ_fine6-h1.ckpt" --is_eval --eval_different_type
# 46.33 -> 47.38
CUDA_VISIBLE_DEVICES=5 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --data_split 8 --experiment_name CWQ_scratch8 1>./logs/CWQ_scratch8.log 2>&1
CUDA_VISIBLE_DEVICES=5 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --data_split 8 --ckpt_4_embedding CWQ_scratch8-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_reasoning --experiment_name CWQ_fine8 1>./logs/CWQ_fine8.log 2>&1
CUDA_VISIBLE_DEVICES=4 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/type_group/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 150 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --early_stop_patience 25 --filter --load_experiment "CWQ_scratch8-h1.ckpt" --is_eval --eval_different_type
CUDA_VISIBLE_DEVICES=3 python main_nsm.py --name CWQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CWQ/type_group/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 150 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --early_stop_patience 25 --filter --load_experiment "CWQ_fine8-h1.ckpt" --is_eval --eval_different_type
