CUDA_VISIBLE_DEVICES=4 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 20 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --experiment_name CFQ_1 1>./logs/CFQ_1.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 20 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --experiment_name CFQ_2 1>./logs/CFQ_2.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 20 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --experiment_name CFQ_3 1>./logs/CFQ_3.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 20 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --reason_with_same_param --pretrain --experiment_name CFQ_5 1>./logs/CFQ_5.log 2>&1 &

CUDA_VISIBLE_DEVICES=2 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --experiment_name CFQ_4 1>./logs/CFQ_4.log 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --data_split 2 --experiment_name CFQ_6 1>./logs/CFQ_6.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --data_split 4 --experiment_name CFQ_7 1>./logs/CFQ_7.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --data_split 6 --experiment_name CFQ_8 1>./logs/CFQ_8.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --data_split 8 --experiment_name CFQ_9 1>./logs/CFQ_9.log 2>&1 &

CUDA_VISIBLE_DEVICES=6 python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --experiment_name CFQ_4 1>./logs/CFQ_4.log 2>&1
CUDA_VISIBLE_DEVICES=6 python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --data_split 2 --experiment_name CFQ_6 1>./logs/CFQ_6.log 2>&1
CUDA_VISIBLE_DEVICES=6 python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --data_split 4 --experiment_name CFQ_7 1>./logs/CFQ_7.log 2>&1
CUDA_VISIBLE_DEVICES=6 python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --data_split 6 --experiment_name CFQ_8 1>./logs/CFQ_8.log 2>&1
CUDA_VISIBLE_DEVICES=6 python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --pretrain --data_split 8 --experiment_name CFQ_9 1>./logs/CFQ_9.log 2>&1

#
CUDA_VISIBLE_DEVICES=3 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 60 --test_batch_size 80 --num_step 4 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 30 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --pretrain --filter --experiment_name CFQ_10 1>./logs/CFQ_10.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 60 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 20 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --pretrain --filter --experiment_name CFQ_11 1>./logs/CFQ_11.log 2>&1 &

# 原始模型迁移
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 20 --word_emb_file word_emb_300d.npy --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --lm_name "lstm" --pretrain --experiment_name CFQ_12 --debug 1>./logs/CFQ_12.log 2>&1 &
#CUDA_VISIBLE_DEVICES=0 python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 20 --word_emb_file word_emb_300d.npy --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --lm_name "lstm" --pretrain --experiment_name CFQ_12 --debug
# 带bert模型迁移
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 15 --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --question_encoder lm --lm_name "bert" --update_last_lm_layer --pretrain --experiment_name CFQ_13 1>./logs/CFQ_13.log 2>&1
# 带kge模型迁移
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --name CFQ --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/CFQ/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 4 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --eps 0.95 --num_epoch 15 --word_emb_file word_emb_300d.npy --use_self_loop --lr 5e-4 --q_type seq --reason_kb --encode_type --loss_type kl --lm_name "lstm" --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --pretrain --experiment_name CFQ_14 1>./logs/CFQ_14.log 2>&1
