#nsm
#CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder /home/hegaole/data/KBQA/Freebase/webqsp/ --checkpoint_dir checkpoint/pretrain/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --experiment_name webqsp_nsm --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb
CUDA_VISIBLE_DEVICES=4 python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --debug --question_encoder bert --experiment_name webqsp_test
# origin
# 68.15 / 67.85
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder lstm --experiment_name webqsp_1 1>./logs/webqsp_1.log 2>&1 &
# 66.75 / 64.67
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder lstm --filter --experiment_name webqsp_1_1 1>./logs/webqsp_1_1.log 2>&1 &
# 迁移cwq的推理部分 71.08
CUDA_VISIBLE_DEVICES=1 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder lstm --filter --finetune --ckpt_4_embedding webqsp_1_1-h1.ckpt --ckpt_4_pretrain CWQ_1_2-37.ckpt --finetune_only_reasoning --experiment_name webqsp_fine_14 1>./logs/webqsp_fine_14.log 2>&1 &
# 迁移原始模型的推理部分 66.50
CUDA_VISIBLE_DEVICES=3 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder lstm --filter --finetune --ckpt_4_embedding webqsp_1_1-h1.ckpt --ckpt_4_pretrain CFQ_12-7.ckpt --finetune_only_reasoning --experiment_name webqsp_fine_19 1>./logs/webqsp_fine_19.log 2>&1 &


# 65.71
# 损失在1.1
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder lm --experiment_name webqsp_3 1>./logs/webqsp_3.log 2>&1 &
# 66.93
# 损失在1.8
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder lm --update_last_lm_layer --experiment_name webqsp_4 1>./logs/webqsp_4.log 2>&1 &

# 56.01(58.21)
# 训练集loss达到3，无法收敛
CUDA_VISIBLE_DEVICES=1 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --question_encoder lm --update_last_lm_layer --experiment_name webqsp_5 1>./logs/webqsp_5.log 2>&1 &
# 62.78
CUDA_VISIBLE_DEVICES=1 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --question_encoder lm --update_last_lm_layer --experiment_name webqsp_5_1 1>./logs/webqsp_5_1.log 2>&1 &

# 正常 65.28
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --reason_with_same_param --experiment_name webqsp_7 1>./logs/webqsp_7.log 2>&1 &
# 使用相同的参数层进行推理 62.29
CUDA_VISIBLE_DEVICES=2 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --reason_with_same_param --experiment_name webqsp_7_1 1>./logs/webqsp_7_1.log 2>&1 &

# finetune whole epoch-11 71.38
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --ckpt_4_embedding webqsp_7-h1.ckpt --ckpt_4_pretrain CFQ_3-11.ckpt --finetune_whole --experiment_name webqsp_fine_3 1>./logs/webqsp_fine_3.log 2>&1 &

# 增加特定关系向量 61.13
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 768 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --add_new_relation_embedding --experiment_name webqsp_8 1>./logs/webqsp_8.log 2>&1 &

# 直接跑 67.18
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --experiment_name webqsp_6 1>./logs/webqsp_6.log 2>&1 &
# 加大batch再跑一次
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 40 --experiment_name webqsp_6_1 1>./logs/webqsp_6_1.log 2>&1 &
# finetune whole epoch-11 67.79
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --ckpt_4_embedding webqsp_7-h1.ckpt --ckpt_4_pretrain CFQ_1-11.ckpt --finetune_whole --experiment_name webqsp_fine_2 1>./logs/webqsp_fine_2.log 2>&1 &
# finetune whole epoch-4 71.02
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --ckpt_4_embedding webqsp_7-h1.ckpt --ckpt_4_pretrain CFQ_2-4.ckpt --finetune_whole --experiment_name webqsp_fine_6 1>./logs/webqsp_fine_6.log 2>&1 &
# finetune whole epoch-7 71.26
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --ckpt_4_embedding webqsp_7-h1.ckpt --ckpt_4_pretrain CFQ_2-7.ckpt --finetune_whole --experiment_name webqsp_fine_7 1>./logs/webqsp_fine_7.log 2>&1 &
# 加载reasoning部分 epoch-11 71.38
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --ckpt_4_embedding webqsp_7-h1.ckpt --ckpt_4_pretrain CFQ_2-11.ckpt --finetune_reasoning --experiment_name webqsp_fine_8 1>./logs/webqsp_fine_8.log 2>&1 &
# 加载instruction部分 epoch-11 68.03
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --ckpt_4_embedding webqsp_7-h1.ckpt --ckpt_4_pretrain CFQ_2-11.ckpt --finetune_instruction --experiment_name webqsp_fine_9 1>./logs/webqsp_fine_9.log 2>&1 &


# 68.15
#CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --ckpt_4_embedding webqsp_7-h1.ckpt --ckpt_4_pretrain CFQ_3-11.ckpt --finetune_reasoning --experiment_name webqsp_fine_4 1>./logs/webqsp_fine_4.log 2>&1 &
# 69.07
#CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --ckpt_4_embedding webqsp_7-h1.ckpt --ckpt_4_pretrain CFQ_3-11.ckpt --finetune_instruction --experiment_name webqsp_fine_5 1>./logs/webqsp_fine_5.log 2>&1 &

# 使用Roberta 67.24
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 768 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_roberta_mean_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "roberta" --update_last_lm_layer --early_stop_patience 40 --experiment_name webqsp_9 1>./logs/webqsp_9.log 2>&1 &

# 暂时延后
# 使用20% cfq-7迁移dim=50的推理部分 webqsp_fine_13_2 72.9
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_13_2 1>./logs/webqsp_fine_13_2.log 2>&1 &
# 使用40% cfq-7迁移dim=50的推理部分 webqsp_fine_13_2 72.9
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_13_2 1>./logs/webqsp_fine_13_2.log 2>&1 &
# 使用60% cfq-7迁移dim=50的推理部分 webqsp_fine_13_2 72.9
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_13_2 1>./logs/webqsp_fine_13_2.log 2>&1 &
# 使用80% cfq-7迁移dim=50的推理部分 webqsp_fine_13_2 72.9
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_13_2 1>./logs/webqsp_fine_13_2.log 2>&1 &

# 使用TransE
# 使用dim=50跑scratch webqsp_10 68.94
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --experiment_name webqsp_10 1>./logs/webqsp_10.log 2>&1 &
# 使用cfq-3迁移dim=50的推理部分 webqsp_fine_13 66.87
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-3.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_13 1>./logs/webqsp_fine_13.log 2>&1 &
# 增大学习率 webqsp_fine_13_1 72.42
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-3.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_13_1 1>./logs/webqsp_fine_13_1.log 2>&1 &
# 使用cfq-7迁移dim=50的推理部分 webqsp_fine_13_2 72.9
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_13_2 1>./logs/webqsp_fine_13_2.log 2>&1 &
# 使用cfq-7迁移dim=50 的问题部分 webqsp_fine_14  59.79
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_instruction --experiment_name webqsp_fine_14 1>./logs/webqsp_fine_14.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_instruction --experiment_name webqsp_fine_14_1 1>./logs/webqsp_fine_14_1.log 2>&1 &
# 使用cfq-7迁移dim=50 的所有部分 webqsp_fine_15  66.93
CUDA_VISIBLE_DEVICES=1 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_whole --experiment_name webqsp_fine_15 1>./logs/webqsp_fine_15.log 2>&1 &
# 迁cwq-best-h1 dim=50 推理部分 webqsp_fine_16 71.87
CUDA_VISIBLE_DEVICES=1 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CWQ_11-h1.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_16 1>./logs/webqsp_fine_16.log 2>&1 &
# 使用cfq-7迁移dim=50的gnn weight部分 webqsp_fine_17 71.63
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_gnn --experiment_name webqsp_fine_17 1>./logs/webqsp_fine_17.log 2>&1 &
# 使用cfq-7迁移dim=50的 score weight 部分 webqsp_fine_18 71.57
CUDA_VISIBLE_DEVICES=7 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_10-h1.ckpt --ckpt_4_pretrain CFQ_11-7.ckpt --finetune --finetune_scoring --experiment_name webqsp_fine_18 1>./logs/webqsp_fine_18.log 2>&1 &

# 使用dim=50使用bert 跑scratch webqsp_12
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --experiment_name webqsp_12 1>./logs/webqsp_12.log 2>&1 &
# 只使用bert 迁移 webqsp_fine_20
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_12-h1.ckpt --ckpt_4_pretrain CFQ_13-7.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_20 1>./logs/webqsp_fine_20.log 2>&1 &
# 使用dim=50使用kge 跑scratch webqsp_13
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --word_emb_file word_emb_300d.npy --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --lm_name "lstm" --early_stop_patience 30 --filter --experiment_name webqsp_13 1>./logs/webqsp_13.log 2>&1 &
# 只使用kge 迁移 webqsp_fine_21
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --word_emb_file word_emb_300d.npy --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --lm_name "lstm" --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_13-h1.ckpt --ckpt_4_pretrain CFQ_14-7.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_21 1>./logs/webqsp_fine_21.log 2>&1 &





# 使用dim=200跑scratch 71.87 webqsp_11
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 20 --filter --experiment_name webqsp_11 1>./logs/webqsp_11.log 2>&1 &
# 使用cfq-3迁移dim=200 的推理部分 72.67 webqsp_fine_10
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_11-h1.ckpt --ckpt_4_pretrain CFQ_10-3.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_10 1>./logs/webqsp_fine_10.log 2>&1 &
# 使用cfq-7迁移dim=200 的推理部分 71.93  webqsp_fine_10_1
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_11-h1.ckpt --ckpt_4_pretrain CFQ_10-7.ckpt --finetune --finetune_reasoning --experiment_name webqsp_fine_10_1 1>./logs/webqsp_fine_10_1.log 2>&1 &
# 使用cfq-3迁移dim=200 的问题部分 64.37 webqsp_fine_11
CUDA_VISIBLE_DEVICES=5 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_11-h1.ckpt --ckpt_4_pretrain CFQ_10-3.ckpt --finetune --finetune_instruction --experiment_name webqsp_fine_11 1>./logs/webqsp_fine_11.log 2>&1 &
# 使用cfq-3迁移dim=200 的所有部分 64.73 webqsp_fine_12
CUDA_VISIBLE_DEVICES=2 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 200 --word_dim 768 --kg_dim 200 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_transe_embedding.npy" --fix_relation_embedding --question_encoder lm --lm_name "bert" --update_last_lm_layer --early_stop_patience 30 --filter --ckpt_4_embedding webqsp_11-h1.ckpt --ckpt_4_pretrain CFQ_10-3.ckpt --finetune --finetune_whole --experiment_name webqsp_fine_12 1>./logs/webqsp_fine_12.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 1e-4 --loss_type kl --reason_kb --relation_emb_file "relations_bert_embedding.npy" --fix_relation_embedding --question_encoder lm --update_last_lm_layer --ckpt_4_embedding webqsp_7-h1.ckpt --ckpt_4_pretrain CFQ_2-11.ckpt --finetune_reasoning --experiment_name webqsp_fine_8 1>./logs/webqsp_fine_8.log 2>&1 &