#nsm
#CUDA_VISIBLE_DEVICES=0 python main_nsm.py --model_name gnn --data_folder /home/hegaole/data/KBQA/Freebase/webqsp/ --checkpoint_dir checkpoint/pretrain/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --experiment_name webqsp_nsm --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb
CUDA_VISIBLE_DEVICES=4 python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --debug --question_encoder bert --experiment_name webqsp_test
# 68.15 origin
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder lstm --experiment_name webqsp_1 1>./logs/webqsp_1.log 2>&1 &
# 67.42
CUDA_VISIBLE_DEVICES=0 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 300 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder lstm --question_encoding_optim --experiment_name webqsp_1_1 1>./logs/webqsp_1_1.log 2>&1 &

# 66.32 use bert encode question and then input lstm
# 最后的损失1.1左右，而不加bert损失在0.8左右，两者均未更新词典
CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder lstm --experiment_name webqsp_2 1>./logs/webqsp_2.log 2>&1 &

CUDA_VISIBLE_DEVICES=6 nohup python main_nsm.py --model_name gnn --data_folder /mnt/jiangjinhao/KBQA/datasets/webqsp/ --checkpoint_dir /mnt/jiangjinhao/KBQA/checkpoint/ --batch_size 20 --test_batch_size 40 --num_step 3 --entity_dim 50 --word_dim 768 --kg_dim 100 --kge_dim 100 --eval_every 2 --encode_type --eps 0.95 --num_epoch 200 --use_self_loop --lr 5e-4 --word_emb_file word_emb_300d.npy --loss_type kl --reason_kb --question_encoder bert --experiment_name webqsp_3 1>./logs/webqsp_3.log 2>&1 &
